apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.org/websocket-services: "covid-19-forecast-service"
  name: covid-19-forecast-nginx-ingress
  namespace: biocomplexity
spec:
  rules:
  - host: bii-forecast.pods.uvarc.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: covid-19-forecast-service
            port:
              number: 8080
  - host: covid19-forecast.pods.uvarc.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: covid-19-forecast-service
            port:
              number: 8080
  - host: bii-forecast.uvadcos.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: covid-19-forecast-service
            port:
              number: 8080
  - host: covid19-forecast.uvadcos.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: covid-19-forecast-service
            port:
              number: 8080