apiVersion: apps/v1
kind: Deployment
metadata:
  name: exceads-dev-deployment
  namespace: biocomplexity
  labels:
    app: exceads-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exceads-dev
  template:
    metadata:
      labels:
        app: exceads-dev
    spec:
      volumes:
      # - name: exceads-nfs-volume
      #   persistentVolumeClaim:
      #     claimName: exceads-nfs-pvc
        - name: exceads-secrets
          secret:
            secretName: exceads-dev-secrets
        - name: exceads-db-secrets
          secret:
            secretName: exceads-dev-db-secrets
        
      imagePullSecrets:
        - name: exceads-dev-registry-secret
      containers:
      - name: exceads-frontend
        image: ghcr.io/nssac/exceads-dev:0.2.4
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http-exceads
        env:
            - name: EXCEADS_DB_PASSWORD_FILE
              value: /run/exceads-db-secrets/db_root_password
            - name: EXCEADS_DB_CONNECTION
              value: localhost:3306/exceads
            - name: EXCEADS_GIT_TOKEN_FILE
              value: /run/exceads-secrets/git_token
            - name: EXCEADS_INSTANCE_NAME
              value: exceads_dev_k8
            - name: EXCEADS_SCIDUCT_TOKEN_FILE
              value: /run/exceads-secrets/sciduct_token
            - name: EXCEADS_SMTP_HOST
              value: out.mail.virginia.edu
            - name: EXCEADS_SMTP_TO
              value: pjp2b@virginia.edu
        # # 3. Inject secrets as ENV variables, from the secrets.yaml spec. (Secrets can also be injected as files in the tree)
        # envFrom:
        # - secretRef: 
        #     name: MYSECRETS
        # All UVARC deployments require a resource spec:
        resources:
          requests:
            memory: "2048Mi"
            cpu: "0.5"
          limits:
            memory: "4096Mi"
            cpu: "2"
        volumeMounts:
        - name: exceads-db-secrets
          readOnly: true
          mountPath: "/run/exceads-db-secrets"
        - name: exceads-secrets
          readOnly: true
          mountPath: "/run/exceads-secrets"
      - name: db
        image: mysql:8.0.20
        # ports:
        # - containerPort: 3306
        #   hostPort: 3306
        #   protocol: TCP
        # - containerPort: 33060
        #   hostPort: 33060
        #   protocol: TCP
        env:
          - name: MYSQL_DATABASE
            value: exceads
          - name: MYSQL_PASSWORD_FILE
            value: /run/exceads-db-secrets/db_exceads_password
          - name: MYSQL_ROOT_PASSWORD_FILE
            value: /run/exceads-db-secrets/db_root_password
          - name: MYSQL_USER
            value: exceads
        resources:
          requests:
            memory: "1024Mi"
            cpu: "0.2"
          limits:
            memory: "2048Mi"
            cpu: "1"
        volumeMounts:
        - name: exceads-db-secrets
          readOnly: true
          mountPath: "/run/exceads-db-secrets"

#
# Deployment file is the basic definition of the pod. It defines the container to run,
# the number of replicas, any ENV variables, VOLS to be mounted, SECRETS, etc.
#
