apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.org/websocket-services: "pepita-dev-service"
  name: pepita-dev-nginx-ingress
  namespace: biocomplexity
spec:
  rules:
  - host: pepita-dev.pods.uvarc.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: pepita-dev-service
            port:
              number: 8080
