apiVersion: v1
kind: Service
metadata:
  name: pepita-dev-service
  namespace: biocomplexity
spec:
  selector:
    app: pepita-dev
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
